version: "3.8"
services:
  furniture_server:
    build:
      context: .
      dockerfile: Dockerfile.furniture
    env_file:
      - .env
    ports:
      - "3000:3000"

  api_server:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    depends_on:
      - furniture_server
    # wir brauchen hier kein ports-Mapping auf 8000, weil Nginx ihn reached

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - api_server
